
GET http://localhost:3000/products

### create a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Vivo T2 -x new",
    "price": 12999

}

### get a product by id
GET  http://localhost:3000/products/6522d48d5cbf3fb3ac50c472

### update a product by id

PATCH  http://localhost:3000/products/64cf470e3cf25bcafc40b3fe
Content-Type: application/json

{   
    "price": 1249
}

### delete a product by id

DELETE  http://localhost:3000/products/64de24bf75dd66fda472c765

### 404 route Not found

GET http://localhost:3000/abc_xyz

###

GET http://localhost:3000/test?name=iMac&price=2399

###

GET http://localhost:3000/test/76899999/imac

###

POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "imacPro",
    "price": 4999
}

###

POST http://localhost:3000/test
Content-Type:application/x-www-form-urlencoded

name=iMac&price=4999


